name: Godot Web CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Устанавливаем Godot
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.3.0
        use-dotnet: false
        include-templates: true

    - name: Import files
      run: | 
        godot --editor --import --headless
        
    - name: Create export folder
      run: | 
        mkdir export

    # Сборка HTML5
    - name: Export HTML5
      run: |
        godot --editor --headless --export-release "HTML5" export/index.html --quit

    # Загрузка результата на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: export/
